version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  web:
    container_name: fastapi_container
    restart: always
    build:
      context: .
      dockerfile: src/Dockerfile
    command: sh -c "alembic upgrade head && uvicorn --factory src.main:create_app --host 0.0.0.0 --port ${API_PORT} --proxy-headers"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/static:/var/www/static
    depends_on:
      - web

volumes:
  postgres_data:
