"""unique=True name table department

Revision ID: 00ac1f5e92ff
Revises: c2a840ad066c
Create Date: 2024-11-16 21:34:49.303700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ac1f5e92ff'
down_revision: Union[str, None] = 'c2a840ad066c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__departments__name'), 'departments', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__departments__name'), 'departments', type_='unique')
    # ### end Alembic commands ###
