"""update model, addad create_at, update_at

Revision ID: 5661204e3c4e
Revises: 5af7d574098a
Create Date: 2024-11-27 21:37:39.981747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5661204e3c4e'
down_revision: Union[str, None] = '5af7d574098a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overtime_day_off_links', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('overtime_day_off_links', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('overtimes', sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('overtimes', sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overtimes', 'update_at')
    op.drop_column('overtimes', 'create_at')
    op.drop_column('overtime_day_off_links', 'update_at')
    op.drop_column('overtime_day_off_links', 'create_at')
    # ### end Alembic commands ###
