"""username unique=True

Revision ID: 5af7d574098a
Revises: e7af5730d89a
Create Date: 2024-11-23 21:02:14.287605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af7d574098a'
down_revision: Union[str, None] = 'e7af5730d89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__users__username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__users__username'), 'users', type_='unique')
    # ### end Alembic commands ###
