"""Add ON DELETE CASCADE

Revision ID: 7f3deeb36256
Revises: aa060cd54451
Create Date: 2024-12-12 20:49:42.527938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3deeb36256'
down_revision: Union[str, None] = 'aa060cd54451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('day_offs_user_oid_fkey', 'day_offs', type_='foreignkey')
    op.create_foreign_key(op.f('day_offs_user_oid_fkey'), 'day_offs', 'users', ['user_oid'], ['oid'], ondelete='CASCADE')
    op.drop_constraint('overtime_day_off_links_day_off_oid_fkey', 'overtime_day_off_links', type_='foreignkey')
    op.drop_constraint('overtime_day_off_links_overtime_oid_fkey', 'overtime_day_off_links', type_='foreignkey')
    op.create_foreign_key(op.f('overtime_day_off_links_overtime_oid_fkey'), 'overtime_day_off_links', 'overtimes', ['overtime_oid'], ['oid'], ondelete='CASCADE')
    op.create_foreign_key(op.f('overtime_day_off_links_day_off_oid_fkey'), 'overtime_day_off_links', 'day_offs', ['day_off_oid'], ['oid'], ondelete='CASCADE')
    op.drop_constraint('overtimes_user_oid_fkey', 'overtimes', type_='foreignkey')
    op.create_foreign_key(op.f('overtimes_user_oid_fkey'), 'overtimes', 'users', ['user_oid'], ['oid'], ondelete='CASCADE')
    op.drop_constraint('users_department_oid_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_department_oid_fkey'), 'users', 'departments', ['department_oid'], ['oid'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_department_oid_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key('users_department_oid_fkey', 'users', 'departments', ['department_oid'], ['oid'])
    op.drop_constraint(op.f('overtimes_user_oid_fkey'), 'overtimes', type_='foreignkey')
    op.create_foreign_key('overtimes_user_oid_fkey', 'overtimes', 'users', ['user_oid'], ['oid'])
    op.drop_constraint(op.f('overtime_day_off_links_day_off_oid_fkey'), 'overtime_day_off_links', type_='foreignkey')
    op.drop_constraint(op.f('overtime_day_off_links_overtime_oid_fkey'), 'overtime_day_off_links', type_='foreignkey')
    op.create_foreign_key('overtime_day_off_links_overtime_oid_fkey', 'overtime_day_off_links', 'overtimes', ['overtime_oid'], ['oid'])
    op.create_foreign_key('overtime_day_off_links_day_off_oid_fkey', 'overtime_day_off_links', 'day_offs', ['day_off_oid'], ['oid'])
    op.drop_constraint(op.f('day_offs_user_oid_fkey'), 'day_offs', type_='foreignkey')
    op.create_foreign_key('day_offs_user_oid_fkey', 'day_offs', 'users', ['user_oid'], ['oid'])
    # ### end Alembic commands ###
