"""addad hours_used table OvertimeDayOffLink

Revision ID: aa060cd54451
Revises: f0a16e728012
Create Date: 2024-12-01 22:58:48.000869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa060cd54451'
down_revision: Union[str, None] = 'f0a16e728012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overtime_day_off_links', sa.Column('hours_used', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overtime_day_off_links', 'hours_used')
    # ### end Alembic commands ###
