"""Initial tables/

Revision ID: e7af5730d89a
Revises: 
Create Date: 2024-11-23 20:33:36.246280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7af5730d89a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk__departments')),
    sa.UniqueConstraint('name', name=op.f('uq__departments__name'))
    )
    op.create_table('users',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('department_oid', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', name='role'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_oid'], ['departments.oid'], name=op.f('users_department_oid_fkey')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk__users'))
    )
    op.create_table('day_offs',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('user_oid', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], name=op.f('day_offs_user_oid_fkey')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk__day_offs'))
    )
    op.create_table('overtimes',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('user_oid', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_oid'], ['users.oid'], name=op.f('overtimes_user_oid_fkey')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk__overtimes'))
    )
    op.create_table('overtime_day_off_links',
    sa.Column('oid', sa.UUID(), nullable=False),
    sa.Column('overtime_oid', sa.UUID(), nullable=False),
    sa.Column('day_off_oid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['day_off_oid'], ['day_offs.oid'], name=op.f('overtime_day_off_links_day_off_oid_fkey')),
    sa.ForeignKeyConstraint(['overtime_oid'], ['overtimes.oid'], name=op.f('overtime_day_off_links_overtime_oid_fkey')),
    sa.PrimaryKeyConstraint('oid', name=op.f('pk__overtime_day_off_links'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overtime_day_off_links')
    op.drop_table('overtimes')
    op.drop_table('day_offs')
    op.drop_table('users')
    op.drop_table('departments')
    # ### end Alembic commands ###
